spring:
  output:
    ansi:
      enabled: always
  datasource:
    h2:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: root
    pg:
      driver-class-name: org.postgresql.Driver #org.postgresql.Driver #com.mysql.jdbc.Driver #org.postgresql.Driver
      url: jdbc:postgresql://192.168.0.15:5432/postgres?currentSchema=eda&characterEncoding=utf8
      username: sys
      password: sysadmin
      hikari:
        maximum-pool-size: 80
        minimum-idle: 30
        max-lifetime: 1800000
        idle-timeout: 180000
        connection-timeout: 30000
        connection-test-query: SELECT 1

#  h2:
#    console.enabled: true  # ?? h2 ? web ??? /h2-console


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always